-- Porjeção Dax teste
-- Categoria: Financeiro

-- Data: 2025-10-15T21:05:31.041Z

Project valor de Domingo = 

VAR DIA = CALCULATE(MAX(fAtendimentos[Data Atendimento]), ALL(dCalendario))

VAR A15 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-1, DIA-1)),DATETIME),1)
VAR B15 = SWITCH(A15, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A14 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-2, DIA-2)),DATETIME),1)
VAR B14 = SWITCH(A14, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A13 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-3, DIA-3)),DATETIME),1)
VAR B13 = SWITCH(A13, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A12 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-4, DIA-4)),DATETIME),1)
VAR B12 = SWITCH(A12, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A11 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-5, DIA-5)),DATETIME),1)
VAR B11 = SWITCH(A11, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A10 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-6, DIA-6)),DATETIME),1)
VAR B10 = SWITCH(A10, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A09 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-7, DIA-7)),DATETIME),1)
VAR B09 = SWITCH(A09, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A08 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-8, DIA-8)),DATETIME),1)
VAR B08 = SWITCH(A08, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A07 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-9, DIA-9)),DATETIME),1)
VAR B07 = SWITCH(A07, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A06 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-10, DIA-10)),DATETIME),1)
VAR B06 = SWITCH(A06, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A05 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-11, DIA-11)),DATETIME),1)
VAR B05 = SWITCH(A05, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A04 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-12, DIA-12)),DATETIME),1)
VAR B04 = SWITCH(A04, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A03 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-13, DIA-13)),DATETIME),1)
VAR B03 = SWITCH(A03, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A02 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-14, DIA-14)),DATETIME),1)
VAR B02 = SWITCH(A02, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)
VAR A01 = WEEKDAY(CONVERT(CALCULATE(MAX(dCalendario[Data]), DATESBETWEEN(dCalendario[Data], DIA-15, DIA-15)),DATETIME),1)
VAR B01 = SWITCH(A01, 1, 1, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0)

VAR C15 = IF(B15 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-1, DIA-1)), 0)
VAR C14 = IF(B14 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-2, DIA-2)), 0)
VAR C13 = IF(B13 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-3, DIA-3)), 0)
VAR C12 = IF(B12 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-4, DIA-4)), 0)
VAR C11 = IF(B11 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-5, DIA-5)), 0)
VAR C10 = IF(B10 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-6, DIA-6)), 0)
VAR C09 = IF(B09 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-7, DIA-7)), 0)
VAR C08 = IF(B08 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-8, DIA-8)), 0)
VAR C07 = IF(B07 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-9, DIA-9)), 0)
VAR C06 = IF(B06 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-10, DIA-10)), 0)
VAR C05 = IF(B05 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-11, DIA-11)), 0)
VAR C04 = IF(B04 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-12, DIA-12)), 0)
VAR C03 = IF(B03 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-13, DIA-13)), 0)
VAR C02 = IF(B02 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-14, DIA-14)), 0)
VAR C01 = IF(B01 = 1, CALCULATE([Vlr. Atendimento], DATESBETWEEN(dCalendario[Data], DIA-15, DIA-15)), 0)

VAR D = C15 + C14 + C13 + C12 + C11 + C10 + C09 + C08 + C07 + C06 + C05 + C04 + C03 + C02 + C01
VAR E = B15 + B14 + B13 + B12 + B11 + B10 + B09 + B08 + B07 + B06 + B05 + B04 + B03 + B02 + B01

RETURN DIVIDE(D, E)