-- Projeção Valor Domingo
-- Categoria: Financeiro

-- Data: 2025-10-15T21:26:30.950Z

Forecast Vlr. Atendimento Domingo = 
VAR DIA_MAX = CALCULATE(MAX(fAtendimentos[Data Atendimento]), ALL(dCalendario))
VAR DiasToCheck = GENERATESERIES(DIA_MAX - 15, DIA_MAX - 1, 1)

VAR Result = 
    SUMX(
        DiasToCheck,
        VAR CurrentDate = [Value]
        VAR DiaSemana = WEEKDAY(CurrentDate, 1)
        VAR IsDomingo = IF(DiaSemana = 1, 1, 0)
        VAR VlrAtendimentoDia = IF(
            IsDomingo = 1,
            CALCULATE([Vlr. Atendimento], FILTER(ALL(dCalendario), dCalendario[Data] = CurrentDate)),
            0
        )
        RETURN VlrAtendimentoDia
    )

VAR TotalDomingos = 
    SUMX(
        DiasToCheck,
        VAR CurrentDate = [Value]
        VAR DiaSemana = WEEKDAY(CurrentDate, 1)
        RETURN IF(DiaSemana = 1, 1, 0)
    )

RETURN DIVIDE(Result, TotalDomingos)