-- teste3
-- Categoria: Financeiro

-- Data: 2025-10-20T02:31:15.255Z

Gross Income Forecast Business Day = 
VAR MinDate = CALCULATE(MIN(dCalendario[Date]), ALL(dCalendario))
VAR MaxDate = CALCULATE(MAX(dCalendario[Date]), ALL(dCalendario))
VAR StartDate = MAX(fBase[Data_A]) + 1
VAR DatesToConsider = FILTER(
    ADDCOLUMNS(
        CALENDAR(StartDate - 15, StartDate - 1),
        "IsBusinessDay", 
            VAR wd = WEEKDAY([Date], 1)
            RETURN IF(wd >= 2 && wd <= 6, 1, 0)
    ),
    [IsBusinessDay] = 1
)
VAR Result = 
    DIVIDE(
        SUMX(
            DatesToConsider,
            CALCULATE([001_Gross Income], FILTER(dCalendario, dCalendario[Date] = [Date]))
        ),
        COUNTROWS(DatesToConsider)
    )
RETURN Result