-- measure-97YIZWMG
-- Categoria: Vendas
-- Descrição: Medida de teste para validação de sessão

-- Data: 2025-10-19T22:46:54.386Z

Total_Sales =
COALESCE(
    CALCULATE(
        SUM(Sales[Amount]),
        ALLSELECTED(Sales)
    ),
    0
)