-- Teste
-- Categoria: Vendas
-- Descrição: TEste testes teste

-- Data: 2025-10-16T13:19:38.154Z

Forecast Vlr. Atendimento Domingo = 
VAR DIA = CALCULATE(MAX(fAtendimentos[Data Atendimento]), ALL(dCalendario))
VAR DiasAnterior15 = CALCULATETABLE(
    ADDCOLUMNS(
        DATESBETWEEN(dCalendario[Data], DIA - 15, DIA - 1),
        "DiaSemana", WEEKDAY(dCalendario[Data], 1),
        "Peso", IF(WEEKDAY(dCalendario[Data],1) = 1, 1, 0),
        "VlrAtendDia", CALCULATE([Vlr. Atendimento], dCalendario[Data])
    )
)
VAR SomaPesada = SUMX(DiasAnterior15, [Peso] * [VlrAtendDia])
VAR SomaPeso = SUMX(DiasAnterior15, [Peso])
RETURN DIVIDE(SomaPesada, SomaPeso)