-- Porjeção de Vendas
-- Categoria: RH
-- Descrição: gdfgdgdfgdf

-- Data: 2025-10-15T22:27:24.369Z


ProjecaoVlrDomingo = 
VAR TodayDate = TODAY()
VAR LastDate = CALCULATE(MAX(fAtendimentos[Data Atendimento]), ALL(dCalendario))
VAR DatesToEvaluate =
    FILTER(
        ADDCOLUMNS(
            CALENDAR(LastDate - 15, LastDate - 1),
            "IsSunday", WEEKDAY([Date], 1) = 1
        ),
        [IsSunday]
    )
RETURN
DIVIDE(
    SUMX(
        DatesToEvaluate,
        CALCULATE([Vlr. Atendimento], dCalendario[Data] = EARLIER([Date]))
    ),
    COUNTROWS(DatesToEvaluate)
)